### ISSUE TITLE
Is it possible to support Angular 4.0+

### ISSUE THREAD

**Issue by gavin1818** [getsaf/shallow-render#104]
I really like this repo, but I notice it doesn't support Angular version lower than 5.0, what's the blocker for making it compatible to lower version angular. If we can't solve that, is there any alternative repository supporting lower version Angular

**Comment by getsaf** [comment]
It's tough to support older versions of Angular with a library because Angular sets hard limits on the version of typescript that are allowed. Many of the type safety features in shallow require newer versions of typescript to function. However, it would be possible to have a build that limits types to be compatible with older Typescript versions from Angular 4. I'm not sure how this would pan out. Best case, it just presents some minor inconveniences, worst case, it cripples the library badly. Aside from that, it's possible to provide compatibility by supplying a compatible jit-reflector (see ,`lib/tools/jit-reflector.ts`).

I'm personally not sure I have time to support this but I would definitely provide some support/code if someone else wants to spearhead the effort. If someone provided 80-90%, I'd help tidy up for a proper build/release.

**Comment by getsaf** [comment]
I thought of one more thing. I use `ng-mocks` to supply mock components in shallow-render. I don't think `ng-mocks` supports anything < Angular 5x. This might be a dealbreaker.

**Comment by getsaf** [comment]
Gonna close this, I'm not sure there's anything to do.
