### ISSUE TITLE
Input bindings are undefined when component has no selector

### ISSUE THREAD

**Issue by ericrav** [getsaf/shallow-render#119]
After updating shallow-render from 7.0.0 to 8.2.0 (and Angular from 7.2.0 to 8.1.0), input bindings on a component with no selector are undefined.

In this example, both logs are `undefined`. Adding a `selector` to the component will fix it though.

```ts
@Component({
  template: '<div></div>',
})
export class TestComponent {
  @Input() public input: object;

  ngOnInit(): void {
    console.log(this.input);
  }
}

describe('TestComponent', () => {
  let shallow: Shallow<TestComponent>;

  @NgModule({
    declarations: [TestComponent],
  })
  class TestingModule {}

  beforeEach(() => {
    shallow = new Shallow(TestComponent, TestingModule);
  });

  it('is undefined', async () => {
    const { instance } = await shallow.render({ bind: { input: { foo: 'bar' } } });
    console.log(instance.input);
  });
});
```

Context:
I'm trying to test a modal component that doesn't have a selector and gets its inputs set directly on the instance. Before this package upgrade, I could set those inputs in a test using the `bind` option.

**Comment by getsaf** [comment]
Thanks for reporting this. Here's what I see:

According to the [Angular Docs](https://angular.io/api/core/Input) it seems like to supply input values to a component, you must supply the values in the template DOM and you can only supply properties to components with selectors:

>> The input property is bound to a DOM property in the template. During change detection, Angular automatically updates the data property with the DOM property's value.

My opinion here is that, in general, your test's interaction with your component should generally mimic how anyone using your component would interact with it. By that, I mean that if you have created an EntryComponent that requires the user of that component to interact with the instance directly, then your test should follow the same pattern.

This sort-of makes me think that I should be "double checking" this behavior in shallow-render. I think that instead of your test simply failing without binding the inputs, that maybe shallow should throw an exception that mentions the misuse of the @Input decorator so it'll be less confusing for the test writer.

Something like:
>> Attempted to set input <INPUT NAME> on <COMPONENT NAME> but <COMPONENT NAME> has no selector and appears to be an EntryComponent.

Then, link to some page on the wiki that has a more detailed explanation of the issue with some possible refactoring suggestions or test-writing approaches.

Hopefully, I have interpreted your issue correctly. Thoughts?

**Comment by getsaf** [comment]
Since you mentioned being able to do this in previous versions, I wanted to mention where the change that prevents us from "binding" to EntryComponents came from.

[Here](https://github.com/getsaf/shallow-render/pull/93/files#diff-b37cfbc420cb72dc2eba949a695ef397L116) is the PR where we stopped applying bindings directly to the component and started using actual Angular templates in shallow. The goal here was to ensure that bindings in shallow-render tests worked exactly like they do in a production app. Namely that the lifecycle hooks function exactly the same in our tests as they do in the real world. When we were binding directly to the component instance we were bypassing a lot of Angular internals and switching to template-based rendering for components with selectors shored that up. Sorry for the rambling, just thought this extra info would be helpful.

**Comment by ericrav** [comment]
Thanks! That makes sense. I think just adding some documentation would resolve this issue.

I see the [FAQ](https://github.com/getsaf/shallow-render/wiki/FAQ#entry-components) has a section about "normal" components rendering an entry component. In my case, I have tests for an entry component itself that now need to set properties directly on the instance and not use bindings. I'm not sure how we would do that because in this example an error is thrown from `ngOnInit` during the `shallow.render`. Can the component instance be accessed before that promise is resolved and before `ngOnInit` is called?

**Comment by getsaf** [comment]
Cool, I'll definitely add something to the docs. May also add the warning too and include a link to the docs in the warning. Appreciate the feedback.

**Comment by getsaf** [comment]
> Can the component instance be accessed before that promise is resolved and before `ngOnInit` is called?

Yes, you should be able to render the component like this:
```typescript
const {instance} = await shallow.render({detectChanges: false});
```

**Comment by getsaf** [comment]
Resolved with new documentation and a more descriptive error
