### ISSUE TITLE
How to provide a class for a mock type

### ISSUE THREAD

**Issue by michaeljota** [getsaf/shallow-render#120]
In my team, we use classes for stub providers. This allow us to have a fresh object with stub calls reset. We currently have an angular module with those replacement being made, but I was wondering if this can be done in the same global way.

**Comment by michaeljota** [comment]
I try to create an Angular Module but the providers there seems that were replaced with the actual values from the original module.

**Comment by getsaf** [comment]
You should be able to do this globally with [alwaysProvide and neverMock](https://github.com/getsaf/shallow-render/wiki/Configuration#shallow-class).

Here's how it would go down:
```typescript
// In your global test-setup
Shallow
  .alwaysProvide({provide: FooService, useClass: FooServiceStub})
  .neverMock(FooService);
```
Here is a functional [StackBlitz](https://stackblitz.com/edit/github-i17jkv?file=examples/using-always-provide.spec.ts) example.

-- Just an opinion here --
I always encourage stubbing directly in the tests because it's "obvious" to the next dev that comes across the test. I generally do not recommend the "collection of stubs" pattern because it's not possible to see that the stubs are being injected just by looking at the test (you'd have to dig to find out where they were provided globally). It also usually ends up with tests that are written to depend on specific behavior/data provided by your stubs which causes a sort-of "magical" coupling of tests-to-stub-data. You can see this in the StackBlitz example on line 52 where the test uses "STUBBED TITLE" which is a "magic string" from the service stub in the expectation.

Anyway, enough of the rant. Thanks for submitting the issue!

**Comment by michaeljota** [comment]
Will try!

About your comment, I know. I'm not a fan either, but at least we are trying to decouple. Before it was just a global module.

And, the stubs don't return anything. I make them that way to assure that they don't share any state. Thanks!
