### ISSUE TITLE
Cannot mock providedIn:'root' service

### ISSUE THREAD

**Issue by apastuhov** [getsaf/shallow-render#128]
Hi, I am not able to use that awesome tool, due to that issue :(

## How to reproduce
I've used code from your examples and extended it with my use-case.

https://stackblitz.com/github/getsaf/shallow-render-stackblitz?file=examples%2Fcomponent-with-service.spec.ts

In file `component-with-service.spec.ts` you can paste next code:

```
import { Component, Injectable, NgModule } from '@angular/core';
import { Shallow } from 'shallow-render';

////// Module Setup //////
@Injectable({
  providedIn: 'root'
})
class ColorService {
  red() {
    return "RED";
  }
  blue() {
    return "BLUE"
  }
}

@Injectable({
  providedIn: 'root'
})
class RedService {
  constructor(private serv: ColorService) {}

  color() {
    return this.serv.red();
  }
}

@Component({
  selector: 'color-label',
  template: '<label>{{redService.color()}}</label>',
})
class ColorLabelComponent {
  constructor(public redService: RedService) {}
}

@NgModule({
  declarations: [ColorLabelComponent],
})
class ColorModule {}
//////////////////////////

describe('component with service', () => {
  let shallow: Shallow<ColorLabelComponent>;

  beforeEach(() => {
    shallow = new Shallow(ColorLabelComponent, ColorModule)
      .mock(RedService, {color: () => 'MOCKED COLOR'});
  });

  it('Uses the color from the RedService', async () => {
    const {element} = await shallow.render();

    expect(element.nativeElement.innerText).toBe('MOCKED COLOR');
  });
});
```

## Actual result
```
Ran 1 of 40 specs - run all1 spec, 1 failure, randomized with seed 62283Spec List | Failures
component with service > Uses the color from the RedService
Expected 'RED' to be 'MOCKED COLOR'.
```

## Expected result
Test passed

**Comment by getsaf** [comment]
Thanks for posting this, I have tried, in the past, to automatically inject modules with `providedIn` but TestBed doesn't support it and Angular doesn't provide any way to find which modules have that tag.
Technically, there is no "root" module in tests, so to support this fully would mean that we inject and mock all root providers in all tests (which we could possibly do, just feels excessive and unwieldy).

You can simulate automatic root injection with `Shallow.alwaysPrivide()` in your global test set up or inject it per-test with `shallow.provide`.

I'm sort of puzzled at why they even created that feature because it breaks the "everything is in the module" pattern.

Gonna leave this open, I'll try (again) to support automatically mocking these in v9 but I'll probably make it optional and defaulted to off.

**Comment by apastuhov** [comment]
Yep, I understand, but it looks like there is a way to test it with TestBed:
https://stackblitz.com/edit/stackoverflow-q-54036099?file=app%2Fhello-world.component.spec.ts

**Note:** In the example you need to remove `provider` from component and add `providedIn: 'root'` to the service. 

So solution is to extend your library with separate `overrideProvider` method, which will use TestBed's method, or extend functionality of `mock` method :)

**Comment by getsaf** [comment]
Ok, I see what you're getting at now. I may look into your suggestion to modify the `mock` method to use `overrideProvider`. I didn't even realize that root providers worked with TestBed until this example :-)

**Comment by getsaf** [comment]
Oh, in the mean-time you may use the `provideMock` or `alwaysProvideMock` feature to mock these things out in your tests with a one-liner.

**Comment by apastuhov** [comment]
yey, sounds good! Thanks a lot for your feedback
