### ISSUE TITLE
angular 9 support

### ISSUE THREAD

**Issue by pablomaurer** [getsaf/shallow-render#149]
should it work or are some changes required? =)

most of the tests are working but some are failing with: 
```
Error: MockOfBooleanValueAccessor class doesn't have @Component decorator or is missing metadata.
```

**Comment by antch** [comment]
It's likely due to this issue: https://github.com/angular/angular-cli/issues/15917#issuecomment-580798025

**Comment by luislode** [comment]
> It's likely due to this issue: [angular/angular-cli#15917 (comment)](https://github.com/angular/angular-cli/issues/15917#issuecomment-580798025)

But what does this mean? Is it a Shallow-render bug? Is there any way to solve this thing?

Thank you.

**Comment by antch** [comment]
If I had to guess I'd say it's a `ng-mocks` issue, but it's impossible to tell without a reproduction. I went ahead and forked the Stackblitz playground and upgraded to Angular 9 -- all the tests pass, but why don't you go ahead and add a new one with a reproduction of this issue?

https://stackblitz.com/edit/shallow-render-ng9

**Comment by antch** [comment]
I will go ahead and piggy-back on this issue to ask @getsaf about Angular 9 support in general. There were some other recent issues where you mentioned a new version of shallow-render specifically supporting Angular 9 that breaks compatibility with previous versions (mainly due to ng-mocks versioning oddities). Any update on that?

**Comment by getsaf** [comment]
I plan on looking at getting an Angular 9 release this weekend. The plan is to upgrade to ng-mocks 9 and drop support for ng-8 and lower in the latest release.

I'll look into this issue if it comes up in the changes but like @antch said, I'd need to be able to reproduce it in order to fix it.

Stay tuned!

**Comment by getsaf** [comment]
I was able to reproduce it. It looks like Angular separated the `TestBed.overrideComponent` function into two so now there's also `TestBed.overrideDirective` and I needed to [make sure I was using the correct one](https://github.com/getsaf/shallow-render/blob/9fbd7f2f77544ed9ed1a0f462162472ffa07401b/lib/tools/ng-mock.ts#L47) for the component being mocked.

Should have a release out soon!

**Comment by getsaf** [comment]
Angular 9 support released!

**Comment by pablomaurer** [comment]
Thank you very much! ❤️
