### ISSUE TITLE
Mocking classes with getters and spying on getter methods

### ISSUE THREAD

**Issue by jbkly** [getsaf/shallow-render#150]
It looks like mocking a class instance  (#143, #144)  doesn't work for classes with getters:

```
@Injectable()
class MyService {
  get myValue() {
    return 'real value';
  }
}

@Component({
  selector: 'my-component',
  template: '<div>{{value}}</div>',
})
class MyComponent {
  public value: string = null;
  
  constructor(private service: MyService) {}

  ngOnInit() {
    this.value = this.service.myValue;
  }
}

/////

class MockService implements MyService {
  get myValue() {
    return 'mock value';
  }
};

describe('using mock class instance with getter', () => {
  let shallow: Shallow<MyComponent>;

  beforeEach(() => {
    shallow = new Shallow(MyComponent, MyModule)
      .mock(MyService, new MockService());
  });

  it('Uses the value from the MockService', async () => {
    const { element } = await shallow.render();

    // fails
    expect(element.nativeElement.innerText).toBe('mock value');
  });
});

```

It also looks like the automatic mocking doesn't spy on getters, whether it's a class instance or a simple object:

```
it('Spies on a getter method of the mockService', async () => {
  const { get } = await shallow.render();

  // fails - Error: <toHaveBeenCalled> : Expected a spy, but got 'mock value'.
  expect(get(MyService).myValue).toHaveBeenCalled();
});
```

I use Jest and I can create my own spy on the mocked object using `jest.spyOn(mockService, 'myValue', 'get');`, but it would be nice if the automatic mocking worked for getters and setters.

I've created a Stackblitz fork here showing the scenarios that aren't working: https://stackblitz.com/edit/shallow-render-fork-jbkly?file=examples%2Fgetters%2Fmocking-service-with-getter.spec.ts

**Comment by getsaf** [comment]
Thanks for the input and the StackBlitz (it was super helpful in understanding the question).

In the beforeEach in your example, the `mock` function is being used incorrectly. You are passing in an instance of a class but shallow expects an object with mock-properties directly on the object (not a class instance with properties on the prototype).

Instead of this:
```typescript
  beforeEach(() => {
    shallow = new Shallow(MyComponent, MyModule)
      .mock(MyService, new MockService());
  });
```

You want this:
```typescript
  beforeEach(() => {
    shallow = new Shallow(MyComponent, MyModule)
      .mock(MyService, {myValue: 'mock value'});
  });
```
If you can mock this way, you will never need to spy on getters (__this is my recommendation to solve your issue__).

I noticed in your StackBlitz that you also tried `provideMock` but `provideMock` does not alter your mock in any way as it is really [just a short-hand](https://github.com/getsaf/shallow-render/wiki/Mocking#provide-a-mock-with-providemock) for:
```typescript
  shallow.provide({provide: MyService, useClass: MyMockService})
       .dontMock(MyService); // <-- Provided Mock classes are un-modified
```

> The following is just my opinion

Getters are generally non-destructive and are interchangeable with variables. Expecting a getter "to be called" is like expecting a variable "to be accessed", such an expectation is usually a code-smell as it is not expecting any particular output or that the variable was used properly. If I'm guessing at the test's intentions, maybe it would be better to expect the proper color value to be displayed in the DOM or emitted in an event would be a better test.

Another note, in your example:
```typescript
    expect(get(ColorService).color$).toHaveBeenCalled();
```

Referencing `color$` in the left-hand-side of the expect block would instantly "call" the getter and this expectation would always be true. The test would never fail.

If you absolutely need to use class-instance-mocks and spy on getters, you'll need to spy on them manually (like you mentioned you are doing with jest).

**Comment by jbkly** [comment]
Got it, thanks for the explanation. Using a mock object instead of a class works fine, maybe it could just be a bit clearer in the documentation that 

> shallow expects an object with mock-properties directly on the object (not a class instance with properties on the prototype)
