### ISSUE TITLE
Examples `component-with-forms` & `component-with-input` don't work

### ISSUE THREAD

**Issue by stevenwoodson** [getsaf/shallow-render#151]
In trying to add some basic form testing to a component, I found the [component-with-forms.spec.ts](https://github.com/getsaf/shallow-render/blob/master/lib/examples/component-with-forms.spec.ts) and [component-with-input.spec.ts](https://github.com/getsaf/shallow-render/blob/master/lib/examples/component-with-input.spec.ts) examples in this codebase to try as a starting point. After many permutations I realized that even the example code in these files used verbatim weren't working. It appears the instance content never gets the update made in the form inputs.

To illustrate, I added these two files to a copy of the shallow render stackblitz at https://stackblitz.com/edit/shallow-render-macv9v

**Comment by getsaf** [comment]
Hey Steve, sorry for the troubles.

It looks like you're using an older version (v6) of Shallow-Render from before I explicitly prevented the core Angular Forms modules from being auto-mocked.

Back then, we auto-mocked everything [except the browser modules](https://github.com/getsaf/shallow-render/blob/v6.2.1/lib/shallow.ts#L12-L14).

Since then, we added the forms modules (and others) [to the list](https://github.com/getsaf/shallow-render/blob/68f82ddfcd503f2fad7243795a083122b4089c04/lib/shallow.ts#L11-L17).

Fortunately, the fix for v6 is simple. In your global karma setup file, add:

```typescript
Shallow.neverMock(FormsModule, ReactiveFormsModule);
```

I've done it in a [fork of your StackBlitz example](https://stackblitz.com/edit/shallow-render-qbzsyj?file=main.ts), looks good!

**Comment by stevenwoodson** [comment]
Ugh such a simple oversight, thanks for taking the time to work up a fork with the adjustment. I'm still getting the hang of this so it's much appreciated!
