### ISSUE TITLE
Testing services?

### ISSUE THREAD

**Issue by dtaylor84** [getsaf/shallow-render#166]
This may be stretching the bailiwick of shallow-render a bit, as it has nothing to do with rendering, but...

Having configured shallow-render to always provide certain global config and replacement modules, it would be useful to take advantage of that config when testing services with dependencies.

I can currently do something unpleasant like this:

```
@Component({ template: '' })
class DummyComponent {}

const { inject } = new Shallow(DummyComponent, MyModule).dontMock(MyService).render();
const service = inject(MyService);
```

I could imagine a slightly nicer (but still dubious) API:

```
const instance = new Shallow(MyService, MyModule).inject(MyService); // or
const { instance } = new Shallow(MyService, MyModule).render();
```

(Or maybe I should stick to using shallow-render to, well, render things...)

**Comment by getsaf** [comment]
You're not the first one to ask this. I usually consider testing services to be pretty easy to do without TestBed because services take in parameters in their constructors without the need for the dependency-injection system. However, it would be nice to have the module-verification side-effect from Shallow while testing a service (eg: verifying the module is setup correctly with all the dependencies needed for the service).

I rather like your suggestion of:
```ts
const { instance } = new Shallow(MyService, MyModule).inject(MyService);
```

Building on that idea, we could return the instance and the injector. That way, your test could inject and control dependencies. Would probably want to come up with a better name than inject/render though since they're overloaded here.

Here's how it plays out in pseudocode:

```ts
let shallow: Shallow<MyService>;
beforeEach(() => {
  shallow = new Shallow(MyService, MyModule)
    .mock(MyAsyncDependency, {$mySubject: new BehaviorSubject('foo')})
});

it('returns the last result from $mySubject', () => {
  cost {instance, inject} = shallow.createInstance(); // or create() .build() or compile() ???
  const $result = instance.doSomething();
  inject(MyAsyncDependency).$mySubject.next('bar');

  expect(await $result.toPromise()).toBe('last thing was bar');
});
```

I don't *think* it'd be difficult to implement since all the plumbing is there already. Would just want to make sure appropriate checks and sane error checks/messages are in place.

Does this sound like a sane approach? I could maybe work on some of this over the weekend unless you want to give it a go?

Either way, I would probably want to have you beta test this since you have a solid use-case already. Would be good to have some feedback from real-world use-cases.

**Comment by dtaylor84** [comment]
Yes, that's just what I was looking for.

Unfortunately I don't think I'll have a chance to try to implement it in the immediate future.

I'd be happy to beta test it, but I am currently stuck with Angular 8 for the next few months.

**Comment by getsaf** [comment]
Man, this took me way longer to get around to implementing than I wanted, but it's done now.

See the release notes for [v10.2.0](https://github.com/getsaf/shallow-render/releases/tag/v10.2.0) or the pr #184 

I will update the docs soon, but it's pretty straight forward so give it a go when you have a chance and let me know how it works for you.

**Comment by dtaylor84** [comment]
Hi, I'm afraid I've moved on to a new role where I'm not using angular, so won't be able to test this in the foreseeable future.

Thanks for implementing it, hopefully it's useful for someone else!
