### ISSUE TITLE
📄 How to reach to author of this project?

### ISSUE THREAD

**Issue by varora1406** [getsaf/shallow-render#172]
Unable to find any contact info on Github profile, or project repository.
Unable to search the person online

I was going to use this project further in my organization, and needed some more one-on-one conversation before heading towards that direction 🙂

**Comment by getsaf** [comment]
I'm the author. We could have the the conversation here in the comments if you think it may benefit other users of the project. I can also be contacted by email me at the same name as my GitHub profile @ gmail.com.

**Comment by varora1406** [comment]
This project helped me today at the place I wanted help.
I might pick time to understand this project in detail, as this one interests me as well.

I want to knew any future work is planned to happen further into this project?
OR is it like complete package as of today ready for usage.

**Comment by getsaf** [comment]
Thanks for your interest. I'm happy to hear that shallow-render has been helpful to you.

At this point, the project is very complete/stable and has generally only required periodic Angular type updates for the last few versions. It will continue to be supported/developed for the foreseeable future.

The only planned features that may be added in the future would be to extend shallow-render to be used to create service instances as well. This feature is being considered is because shallow-render has a very powerful module-mocking system that can be re-used for complex service tests. I will probably add this support to the next major release.

That being said, I think shallow-render is capable of any kind of rendering test you may have. As with any tests, the more complex your scenario, the more complex the test will be but if you are using shallow-render, your tests will require significantly less code and will be far easier to read when compared to standard TestBed tests.

Let me know if you have any other questions. Hope you get to use shallow-render in your project!
