### ISSUE TITLE
@ngrx/component ngrxLet directive in tests

### ISSUE THREAD

**Issue by FrEaKmAn** [getsaf/shallow-render#202]
Hi

I'm using ngrx and it's ngrxLet directive. Problem is that in tests variables are not resolved, for example

```
<div *ngrxLet="documentID$ as documentID">
    {{ documentID }}
</div>
```

documentID is undefined. I have included `Shallow.alwaysRenderStructuralDirectives` without success.

I have included the test to showcase the issue: https://stackblitz.com/edit/angular-testing-56s1ix?file=app%2Fapp.component.spec.ts

I don't know if issue is on ngrx side or I need to include something extra to make it work?

**Comment by getsaf** [comment]
Remember that *everything* in the module except for your test component is mocked by default. This means the `ngrxLet` directive is mocked too so you are not testing with the real `ngrxLet`.

There are technically several ways to address this but the simple approach is that because NGRX directives are generally effect-free utilities, you can tell Shallow Render never mock NGRX stuff so you can depend on it's behaviors in your tests.

[Here](https://stackblitz.com/edit/angular-testing-hm62gg?file=app%2Fapp.component.spec.ts) is an example that works.
The change was to simply never mock NGRX like this:

```ts
    Shallow.neverMock(ReactiveComponentModule);
```

Another note is that the `alwaysRenderStructuralDirectives` is just a way to tell Shallow Render how to render *mocked* structural directives so it was not necessary.

**Comment by FrEaKmAn** [comment]
Amazing, it works. Thank you for your help and amazing project.
