### ISSUE TITLE
Ngxs/store @select decorator compatibility 

### ISSUE THREAD

**Issue by juracy** [getsaf/shallow-render#36]
I couldn't test components using @select decorator of ngxs/store, I'm without new ideas how to test it!

if I try to provide store I've got this error:

```  ● LoginComponent Shallow Render › should log in

    SelectFactory not connected to store!

      at LoginComponent.createSelect (node_modules/@ngxs/store/bundles/ng:/@ngxs/store/packages/store/src/select.ts:45:15)
      at LoginComponent.get [as conf] (node_modules/@ngxs/store/bundles/ng:/@ngxs/store/packages/store/src/select.ts:73:1)
      at Object.View_LoginComponent_0._co [as updateDirectives] (ng:/DynamicTestModule/LoginComponent.ngfactory.js:237:31)
      at Object.debugUpdateDirectives [as updateDirectives] (../../../../../execroot/angular/packages/core/src/view/services.ts:384:19)
      at checkAndUpdateView (../../../../../execroot/angular/packages/core/src/view/view.ts:359:12)
```

If I try to provide store and don't mock it, I've got this one:

``` FAIL  src/app/auth/login.component.spec.ts
  ● LoginComponent Shallow Render › should log in

    StaticInjectorError(DynamicTestModule)[Store -> StateStream]:
      StaticInjectorError(Platform: core)[Store -> StateStream]:
        NullInjectorError: No provider for StateStream!```

**Comment by getsaf** [comment]
I'm traveling most of the day today but I just glanced at the @select decorator for that library and it looks like a simple solution.

https://github.com/ngxs/store/blob/master/packages/store/src/decorators/select.ts#L35

The error you're seeing comes from there. It's looking for a static `store` property on the `SelectFactory` class. Looks like there are two options.

You could are up a `SelectFactory` which sets the property or just assign a mock store to `SelectFactory.store` and you should be good to go.

Here is the property I'm talking about.
https://github.com/ngxs/store/blob/master/packages/store/src/decorators/select.ts#L13

Remember this is a static property so it will bleed across tests unless you clean it up your mock in an afterEach!

Let me know if that works out for you. I'll check back later today or tomorrow.

**Comment by juracy** [comment]
Hi, thanks for quick feedback, unhappely SelectFactory isn't exposed by ngxs/store ... 
I've just made an example here: https://stackblitz.com/edit/angular-shallow-render-select

any ideas?

**Comment by getsaf** [comment]
Cool, the StackBlitz helped me understand a lot. Here's what I found. Looks like since they are using a `forRoot` + decorators, things get a little weird which is why they are using static properties behind the scenes.

Unfortunately, if you want to use `dontMock` or `neverMock` the thing you pass into the `dontMock`/`neverMock` method must `===` the module/provider/component/etc from the component's module. In this case, when using `NgxsModule.forRoot()` in the component's module, the `forRoot` method yields a singleton object (an `NgModuleWithProviders`) that we must gain access to so we have a thing that `Shallow` can `===` compare to skip mocking.

My solution was simply to export the rooted `NgxsModule` and pass that into the `dontMock` in the spec. You may use `neverMock` in the same manner if you want to just do it once for all your specs.

This was an interesting problem to solve. I may try to think of a way to make this more intuitive or put something in the docs for the next person to run across something like this.

Here's my fork of your StackBlitz:
https://stackblitz.com/edit/angular-shallow-render-select-specs?file=src/app/app.component.spec.ts

**Comment by juracy** [comment]
@getsaf thank you, it solves the problem with @select and works for this case.

But in a real world app I still have some problems (may another issue, and another stackblitz ...), It seems ngxs/store need to be initialized in the root module, not in a feature or shared module, so when I need to test a feature module (which doesn't have NgxsModule.forRoot() (only forFeature() or nothing), I still got that message.

Is there anyway to inject (not replace or mock) a new dependency in the MockModule?

**Comment by juracy** [comment]
Of course I can create a Mock module (a la TestBed) with my requirements (including NgxsModule.forRoot), but I'd prefer to test my original module too! :)

**Comment by getsaf** [comment]
Yes, there is `Shallow.alwaysProvide(<any angular style provider>)` and `Shallow#provide(<any angular style provider>)`.

I've run into some of the same scenarios myself where an application has a handful of `forRoot`ed configurations. I've got a [small mention of it](https://github.com/getsaf/shallow-render/wiki/Mocking#global-providers-with-alwaysprovide) in the wiki with an example that may help.

**Comment by getsaf** [comment]
Another note is that because these are truly *Angular* style providers, you can do all the weird things Angular allows like `{provide: MyThingOrToken, useClass/useValue/useFactory: MyMock}`. I generally avoid those because they allow skirting type-safety but they are available because I know some libraries/frameworks operate outside the type-safe safety net.

**Comment by getsaf** [comment]
Oh, one more thing. If you find yourself really needing to wrap a test module around your component's module, you also may try creating a helper method to do `NgxsModule` wrapping for you like this:

You could have a common wrapper helper for your specs:
```typescript
export function wrapNgxs(actualModule: Type<any>, states: any[]) {
  const ngxsModule = NgxsModule.forRoot(states);
  @NgModule({
    imports: [
      MyComponentModule, // Include your actual module so it can be verified
      ngxsModule, // For your custom ngxs module..
    ] 
  })
  class ModuleForSpecs {
    static ngxsModule = ngxsModule;
  }
};
```

Then in specs that care about ngxs stuff you can just wrap your component module like so:

```typescript
  const testModule = wrapNgXs(MyModule, [ConfigState])
  shallow = new Shallow(MyComponent, testModule)
    .dontMock(testModule.ngxsModule);
```

Of course, this is all off-the-cuff, but I think it would work. Sorry for all the replies here, there are just so many ways to attack things in Angular, it's hard to stop at just one!

**Comment by juracy** [comment]
Humm, my knowledge is limited in this area... I liked wrapNgxs approach, but I don't had success...


```
Type LoginComponent is part of the declarations of 2 modules: AuthModule and DynamicTestModule!
Please consider moving LoginComponent to a higher module that imports 
AuthModule and DynamicTestModule.
You can also create a new NgModule that exports and includes 
LoginComponent then import that NgModule in AuthModule and DynamicTestModule.
```

Of course, I made some fixes in snippet:

```typescript
export function wrapNgxs(actualModule: Type<any>, states: any[]) {
  const ngxsModule = NgxsModule.forRoot(states)
  @NgModule({
    imports: [
      ngxsModule, // For your custom ngxs module..
      actualModule, // Include your actual module so it can be verified
    ],
  })
  class ModuleForSpecs {
    static ngxsModule = ngxsModule
  }

  return ModuleForSpecs
}

const testModule = wrapNgxs(AuthModule, [])

describe('LoginComponent TestBed', () => {
  let shallow: Shallow<LoginComponent>
  const actions = []

  beforeEach(() => {
    shallow = new Shallow(LoginComponent, testModule)
      .dontMock(testModule.ngxsModule)
```

**Comment by getsaf** [comment]
Glad it worked out! I'm going to close this issue.
