### ISSUE TITLE
Unable to mock component methods

### ISSUE THREAD

**Issue by checketts** [getsaf/shallow-render#52]
I apologize if I'm just misusing the library. Here is a test case demonstrating the failure: https://stackblitz.com/edit/shallow-render-jz9ubo?file=examples/multiple-components.spec.ts

If I have a child component and I need to mock out a method that is called (`getThing()` in the code below):

```
class AwesomeListComponent {
  @Input() topItem: string;
  @Input() boldTopItem = false;
  @ViewChild('listContainer') listContainer: ListContainerComponent;

  ngAfterViewInit(): void {
    console.log(this.listContainer.getThing())
  }

}
```

I would expect to be able to mock it out by: `.mock(ListContainerComponent, {getThing : () => 'Test Thing'});`

However I get `TypeError: this.listContainer.getThing is not a function`

**Comment by getsaf** [comment]
Hey, good question. This is the intended behavior, generally we only mock output/input properties on mocked components to encourage testing through the DOM instead of calling instance methods.

`ViewChild` and `ContentChild` present exceptions to the rules above. For now, you'll probably want to use `dontMock` for this test.
(seen here)
https://stackblitz.com/edit/shallow-render-z2mq6c?file=examples/multiple-components.spec.ts

I may spend some time adding a feature that will allow you to `.mock(Component, {stub: () => 'stub response'})`, which would allow you to do exactly what you intuitively expected to do with your test. I probably won't get to that until this weekend though.

**Comment by getsaf** [comment]
Got this feature added! Give it a go in the latest version!

**Comment by checketts** [comment]
Yes! This works perfectly! (Sorry for the delay in trying it out.)

I am so excited that my tests are shorter and must simpler to read (now it's time to train the team!)

Thanks so much for adding this!
