### ISSUE TITLE
TwoWay Databinding does not update bindings

### ISSUE THREAD

**Issue by buehler** [getsaf/shallow-render#63]
Hey there!
First of all, awesome piece of work!

It really does simplify the process of testing angular applications :)

But I have one issue that makes me pulling my hair out of my head:

I've got a component that has a two way binding implemented on in:

```typescript
@Component({
  selector: 'bc-checkbox',
  templateUrl: './checkbox.component.html',
  styleUrls: ['./checkbox.component.scss'],
})
export class CheckboxComponent {
  private static idCounter: number = 0;

  @Input() public id: string = `bc-checkbox-${++CheckboxComponent.idCounter}`;
  @Input() public disabled: boolean = false;
  @Input() public checked: boolean = false;
  @Output() public checkedChange: EventEmitter<boolean> = new EventEmitter();

  public get checkedValue(): boolean {
    return this.checked;
  }

  public set checkedValue(value: boolean) {
    this.checked = value;
    this.checkedChange.emit(this.checked);
  }

  public change(): void {
    if (this.disabled) {
      return;
    }
    this.checkedValue = !this.checkedValue;
  }
}
```

```html
<div (click)="change()" class="bc-checkbox">
  <input id="{{id}}" type="checkbox" [disabled]="disabled" [checked]="checkedValue" (change)="change()">
  <label for="{{id}}">
    <ng-content></ng-content>
  </label>
</div>
```

Now I want to unit test this binding (checked):

```typescript

it('should emit the checked value on click on input', fakeAsync(async () => {
    const { find, bindings } = await shallow.render(
      `<bc-checkbox [(checked)]="checked"></bc-checkbox>`,
      { bind: { checked: false } },
    );
    find('input').triggerEventHandler('change', null);

    expect(bindings.checked).toBe(true);
  }));

```

But checked is not set to `True`.
Event when I use `fixture.detectChanges`.

Can you help me? :)

Cheers and a nice day

**Comment by getsaf** [comment]
Hey, thanks for the compliment, glad it's helping!

I think the confusion may be due to using a 2-way binding in the test. Maybe I'm misunderstanding the example, but it *looks* like your intention is to test the `checkedChange` event emits when the `checked` property changes.

If that's the case, you could write a test w/out the 2-way binding:
```typescript
it('emit the checked value on change', fakeAsync(async () => {
    const { find, instance } = await shallow.render(
      `<bc-checkbox [(checked)]="checked"></bc-checkbox>`,
      { bind: { checked: false } },
    );
    find('input').triggerEventHandler('change', null);

    expect(instance.checkedChange).toHaveBeenCalledWith(true);
  }));
```

The nice part here is that the test focuses solely on the component's behavior. In your example, it sort-of felt like we were testing that Angular 2-way binds things and that's something that Angular is responsible for, not your component.

Let me know if this addresses your issues. I feel like it's possible I misinterpreted the example.

**Comment by buehler** [comment]
Oh.. very nice, I'm gonna try that. And yes, you were right when you wrote "Testing Angular 2-way" :-) I'm definitly not responsible for their code.

Gonna try that right now.

**Comment by buehler** [comment]
Works like a charm :-)

**Comment by buehler** [comment]
Thanks for the help!
