### ISSUE TITLE
Button disabled property not updating

### ISSUE THREAD

**Issue by stephenwil** [getsaf/shallow-render#92]
Hi,
  I've got a simple component, where a button is disabled or enabled on the validation of an input field.
I'm finding that the tests are running in reverse order, and more importantly, nativeElement.disabled is always false, whereas componentInstance.disabled is always true.
This is even after either fixture.detectChanges(); and await fixture.detectChange

**Comment by getsaf** [comment]
I've got an example spec that flips the disabled flag on a button. Could you reproduce the issue and post it here so we can debug?

https://stackblitz.com/edit/github-znkk6c?file=examples/simple-component.spec.ts

**Comment by stephenwil** [comment]
Hi, Have a look at the multiple components test here:
https://stackblitz.com/edit/github-mj7sec?file=examples%2Fmultiple-components.spec.ts

2 simple tests, testing for a button property. See console logs.
(Incidently, not sure why ngInit seems to be called twice...)

**Comment by getsaf** [comment]
Thanks for helping with the StackBlitz example, it helped. I see what's going on here..

Looks like that button is a `MatButton` component, which is mocked. Since it's mocked we won't see the behavior of `MatButton` propagate to the DOM unless you specifically did a `dontMock(MatButton)`. It looks like you were already close to the "shallow" solution which is to simply assert on the parameters that were passed into `MatButton` instead of testing the the side-effect of setting the `[disabled]` attribute on the `MatButton`.

In short, I'd recommend always asserting on mocked components' instance input bindings when shallow-testing:

```typescript
  it('button is enabled on valid postcode', async () => {
    const { find, fixture } = await shallow.render(`
      <address-component postcode="ML12SW"><address-component>
    `);

    const button = find('button');
    expect(button).toHaveFound(1);
    expect(button.componentInstance.disabled).toEqual(false);
  });
```

Here's my modifications to that stackblitz:
https://stackblitz.com/edit/github-mj7sec?file=examples%2Fmultiple-components.spec.ts

Let me know if this works out for you and go ahead and close the issue if you're good.

**Comment by stephenwil** [comment]
Brilliant, thanks for the assistance!
